name: Build Berkelium and Kivy-Berkelium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up dependencies
    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils-gold chrpath git-core cython python-dev cmake

    # Step 3: Clone and build Berkelium
    - name: Clone Berkelium repository
      run: |
        git clone https://github.com/sirikata/berkelium.git
        cd berkelium
        git checkout chromium11
        util/build-chromium.sh --deps --force
        cmake . -DCMAKE_BUILD_TYPE=Release
        git submodule update --init --recursive
        make

    # Step 4: Clone and build Kivy-Berkelium
    - name: Clone Kivy-Berkelium repository
      run: |
        git clone git://github.com/kivy/kivy-berkelium
        cd kivy-berkelium
        make

    # Step 5: Move the .kex file to the dist folder
    - name: Rename the Kivy-Berkelium zip file
      run: |
        mv dist/berkelium-1.3.linux-x86_64.zip dist/berkelium-1.3.linux-x86_64.kex

    # Step 6: Save the .kex file as an artifact
    - name: Upload .kex file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: berkelium-1.3-linux-x86_64
        path: dist/berkelium-1.3.linux-x86_64.kex
        
